# Generated by Django 4.2.1 on 2023-08-21 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spirit_topic', '0004_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
