# Generated by Django 4.2.1 on 2023-09-06 05:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('spirit_topic', '0005_topic_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
